### ISSUE TITLE
is this available?

### ISSUE THREAD

**Issue by matthewmueller** [enquirer/prompt-password#1]
would like to use it :-)

**Comment by jonschlinkert** [comment]
Indeed it is lol. Sorry I got ahead of myself. I created all of the prompts, then I decided to try to make them as standalone as possible (so you wouldn't necessarily need enquirer), and it took longer than I expected. But I'm pretty sure this one's finished.

**Comment by jonschlinkert** [comment]
@matthewmueller it's published. Working on unit tests, and some tools to make unit testing easier for the prompts. let me know if you have any issues with this in the meantime if you decide to kick the tires

**Comment by matthewmueller** [comment]
awesome, thanks! i'll be giving this a shot again over the next couple days :-)

**Comment by jonschlinkert** [comment]
no problem, let me know if you have any feedback at all. I'd love to make these libs as usable as possible

**Comment by jonschlinkert** [comment]
Forgot to update this, but the module was published a while back and should be working. let me know if you have any questions!

**Comment by matthewmueller** [comment]
great, thanks!
