### ISSUE TITLE
Don't expose password length

### ISSUE THREAD

**Issue by joshbetz** [enquirer/prompt-password#2]
I can set the mask to something like `i => ''`, but if I paste a password, the prompt is output over and over again:

```
Password:
Password:
Password:
Password:
Password:
```

**Comment by joshbetz** [comment]
I think it has to be something that causes a line break in the terminal. A short password doesn't trigger it.

**Comment by joshbetz** [comment]
Commenting out this line fixes it:

https://github.com/enquirer/readline-ui/blob/master/index.js#L137

```
this.appendedLines = footerHeight;
```

**Comment by doowb** [comment]
@joshbetz can you provide a code example and an example of a long string that would cause the line break?

Thanks for digging in and pointing to the line in `readline-ui`. This may just be a calculation that's done on the actual input vs what's being shown, or it's where the cursor position is set.

**Comment by joshbetz** [comment]
I'm using the prompt.mask.js example, but changing the mask to `mask: _ => '',`:

```
var Prompt = require('..');
var prompt = new Prompt({
  type: 'password',
  message: 'Enter your password',
  name: 'password',
  mask: _ => '',
});

prompt.run()
  .then(function(answers) {
    console.log(answers)
  });
```

I'm just using a very long string to reproduce:

`3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob3QN4KnbrIajNeYpJvQP2Pu15nNNKob`

**Comment by doowb** [comment]
Thanks for the additional information.

I think removing that one line will break other prompts. I started looking into how this could be fixed for all prompts and I think it might be something we can change [in this section of code](https://github.com/enquirer/readline-ui/blob/master/index.js#L93-L98) but I'm not sure exactly what yet.

If you have any ideas, please let me know and we can try to get it fixed.

**Comment by jonschlinkert** [comment]
I'm a little confused about the point of the issue. Is this issue about the bug that's happening when an empty string is returned from the `mask` function? Or that a length is exposed (somewhere that isn't mentioned in this issue)?

**Comment by joshbetz** [comment]
> Is this issue about the bug that's happening when an empty string is returned from the mask function?

This. I don't think it has to be an empty string. Any fixed length string will do it.

**Comment by doowb** [comment]
Closing as this repository is being archived in lieu of [Enquirer 2.0](https://github.com/enquirer/enquirer). Please direct all questions, issues and feature requests to that repository.
